## 使用druid配置数据源
spring:
  application:
    name: basic-supplier-dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: matrix
      password: Matrix_2018
      url: jdbc:mysql://49.4.10.211:8635/erp_supplier?characterEncoding=UTF-8
      max-active: 20
      validation-query: SELECT 1 FROM DUAL
      initial-size: 10
      max-wait: 60000

## eureka server 地址， 根据实际情况设置eureka server地址
eureka:
  client:
    service-url:
      defaultZone: http://49.4.10.118:8080/eureka
  instance:
    prefer-ip-address: true

server:
  servlet:
    context-path: /supplier
    
erp:
  sys: ZUUL-SERVER
  wms: ZUUL-SERVER
