spring:
  profiles:
    active: dev

## 设置日志级别
logging:
  level:
    root: info

## web服务开启端口
# context-path 表示所有api的前缀
server:
  port: 8080

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
    call-setters-on-nulls: true

pagehelper:
  row-bounds-with-count: true
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: com.github.pagehelper.dialect.helper.MySqlDialect

