## 使用druid配置数据源
spring:
  application:
    name: matrix-quality
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: Matrix_2018
      url: jdbc:mysql://172.16.0.171:8635/matrix_quality?characterEncoding=UTF-8
      max-active: 20
      validation-query: SELECT 1 FROM DUAL
      initial-size: 10
      max-wait: 60000

## eureka server 地址， 根据实际情况设置eureka server地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.default.svc.cluster.local:8080/eureka
  instance:
    prefer-ip-address: true

server:
  servlet:
    context-path: /quality

erp:
  product: ERP-PRODUCT
  supplier: SUPPLIER-SERVER
  sys: ERP-SYS
  warehouse: MATRIX-WAREHOUSE
  images: IMAGES-SERVER
  purchase: MATRIX-PURCHASE-ORDER
  wms: MATRIX-WMS
